QualyTeamWebSite/QualyTeam.WebSite/ViewModels/DocumentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using QualyTeam.Service.Dto;
using System.Web;
using System.Collections.Generic;
using QualyTeam.WebSite.Helper;

namespace QualyTeam.WebSite.ViewModels
{
    [Serializable]
    public class DocumentViewModel
    {
        [Display(Name = "Codigo", Prompt = "Código", Order = 0)]
        [Required(ErrorMessage = "O campo Código não é válido.")]
        [CodigoValidator]
        public int Codigo { get; set; }

        [Display(Name = "Titulo", Prompt = "Título", Order = 1)]
        [StringLength(255)]
        [Required(ErrorMessage = "O campo Título não é válido.")]
        public string Titulo { get; set; }

        [Display(Name = "Processo", Prompt = "Título", Order = 2)]
        [StringLength(255)]
        [Required(ErrorMessage = "O campo Processo não é válido.")]
        public string Processo { get; set; }

        [Display(Name = "Categoria", Prompt = "Categoria", Order = 3)]
        [StringLength(255)]
        [Required(ErrorMessage = "O campo Categoria não é válido.")]
        public string Categoria { get; set; }

        [Required][Helper.FileExtensionsAttribute("pdf,xls,doc", ErrorMessage = "Extensão do arquivo incorreta (extensões válidas: xls, doc, pdf).")]
        public HttpPostedFileBase Arquivo { get; set; }

        public byte[] ArquivoByte { get; set; }

        public string ArquivoExt { get; set; }

        public DocumentViewModel()
        {

        }

        public DocumentViewModel(DocumentDto dto)
        {
            Codigo = dto.Codigo;
            Titulo = dto.Titulo;
            Processo = dto.Processo;
            Categoria = dto.Categoria;
            ArquivoByte = dto.Arquivo;
            ArquivoExt = dto.ArquivoExt;
        }
    }

    public static class DocumentViewModelMapper
    {
        public static DocumentViewModel ToViewModel(this DocumentDto dto)
        {
            return new DocumentViewModel(dto);
        }
        public static DocumentDto ToDto(this DocumentViewModel dvm)
        {
            var extDvm="";
            bool ext;
            if (dvm.Arquivo != null)
                ext = _mappings.TryGetValue(dvm.Arquivo.ContentType, out extDvm);
            return new DocumentDto
            {
                Titulo = dvm.Titulo,
                Codigo = dvm.Codigo,
                Arquivo = (dvm.Arquivo != null && extDvm != "") ? Helper.Util.FileToByteArray(dvm.Arquivo) : null,
                Categoria = dvm.Categoria,
                Processo = dvm.Processo,
                ArquivoExt = extDvm
            };
        }

        private static IDictionary<string, string> _mappings = new Dictionary<string, string>(StringComparer.InvariantCultureIgnoreCase)
        {
            {"application/vnd.ms-excel", "xls"},
            {"application/msword", "doc"},
            {"application/pdf", "pdf"}
        };
    }
}

QualyTeamWebSite/QualyTeam.WebSite/Controllers/DocumentController.cs
using QualyTeam.WebSite.QualyTeamService;
using QualyTeam.WebSite.ViewModels;
using QualyTeam.Service.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QualyTeam.WebSite.Controllers
{
    public class DocumentController : Controller
    {
        private readonly ServiceClient _service;

        public DocumentController()
        {
            _service = new ServiceClient();
        }

        public ActionResult Index()
        {
            return RedirectToAction("DocumentsList");
        }

        public ActionResult DocumentsList(string message = "", int status = 0, string filterTag = "")
        {
            if (status != 0)
            {
                ViewBag.FeedbackMensagem = message;
                if (status == (int)FeedbackStatus.Success)
                    ViewBag.FeedbackStatus = "Sucesso";
                if (status == (int)FeedbackStatus.Fail)
                    ViewBag.FeedbackStatus = "Operação cancelada";
            }

            var documents = _service.ListDocuments();

            switch (filterTag)
            {
                case "codigo":
                    documents = documents.OrderBy(d => d.Codigo).ToList();
                    break;
                case "processo":
                    documents = documents.OrderBy(d => d.Processo).ToList();
                    break;
                case "categoria":
                    documents = documents.OrderBy(d => d.Categoria).ToList();
                    break;
                default:
                    documents = documents.OrderBy(d => d.Titulo).ToList();
                    break;
            }
            return View(documents.ConvertAll(d => d.ToViewModel()));
        }

        public ActionResult Save(string message = "", int status = 0)
        {
            if (status != 0)
            {
                ViewBag.FeedbackMensagem = message;
                if (status == (int)FeedbackStatus.Success)
                    ViewBag.FeedbackStatus = "Sucesso";
                if (status == (int)FeedbackStatus.Fail)
                    ViewBag.FeedbackStatus = "Operação cancelada";
            }
            return View(new DocumentViewModel());
        }

        [HttpPost]
        public ActionResult Save(DocumentViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (_service.GetDocumentByCodigo(vm.Codigo) == null)
                {
                    var feedback = _service.SaveDocument(vm.ToDto());
                    if (feedback.Status == FeedbackStatus.Success)
                        return RedirectToAction("DocumentsList", new { message = feedback.Mensagem, status = (int)feedback.Status });
                    else
                        return RedirectToAction("Save", new { message = feedback.Mensagem, status = (int)feedback.Status });
                }
                else
                    return View(vm);
            }
            else
                return View(vm);
        }

        public FileResult DownloadFile(int codigo)
        {
            var document = _service.GetDocumentByCodigo(codigo).ToViewModel();
            return File(document.ArquivoByte, document.ArquivoExt, string.Format("Documento-Codigo{0}.pdf", document.Codigo.ToString()));
        }
    }
}

QualyTeamWebSite/QualyTeam.WebSite/Views/Document/DocumentsList.cshtml
@model IEnumerable<QualyTeam.WebSite.ViewModels.DocumentViewModel>

@using (Html.BeginForm("DocumentsList", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    if (ViewBag.FeedbackMensagem != null)
    {
        @Html.Raw("<script>");
        @Html.Raw("popFeedbackAlert('" + ViewBag.FeedbackStatus + "', '" + ViewBag.FeedbackMensagem + "');");
        @Html.Raw("</script>");
    }

    @Html.ActionLink("Cadastrar novo documento", "Save", "Document")
    <div class="limiter">
        <div class="container-table100">
            <div class="wrap-table100">
                <div class="table100 ver3 m-b-110">
                    <div class="table100-head">
                        <table>
                            <thead>
                                <tr class="row100 head">
                                    <th class="cell100 column1">@Html.ActionLink("Codigo", "DocumentsList", new { filterTag = "codigo" })</th>
                                    <th class="cell100 column2">@Html.ActionLink("Titulo", "DocumentsList", new { filterTag = "titulo" })</th>
                                    <th class="cell100 column3">@Html.ActionLink("Processo", "DocumentsList", new { filterTag = "processo" })</th>
                                    <th class="cell100 column4">@Html.ActionLink("Categoria", "DocumentsList", new { filterTag = "categoria" })</th>
                                    <th class="cell100 column5">@Html.DisplayNameFor(modelItem => modelItem.Arquivo)</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="table100-body js-pscroll">
                        <table>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="row100 body">
                                        <td class="cell100 column1">@Html.DisplayFor(modelItem => item.Codigo)</td>
                                        <td class="cell100 column2">@Html.DisplayFor(modelItem => item.Titulo)</td>
                                        <td class="cell100 column3">@Html.DisplayFor(modelItem => item.Processo)</td>
                                        <td class="cell100 column4">@Html.DisplayFor(modelItem => item.Categoria)</td>
                                        <td class="cell100 column5">@Html.ActionLink("[Download]", "DownloadFile", new { codigo = item.Codigo })</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

QualyTeamWebSite/QualyTeam.WebSite/Views/Document/Save.cshtml
@model QualyTeam.WebSite.ViewModels.DocumentViewModel
@using QualyTeam.WebSite.Helper
@using (Html.BeginForm("Save", "Document", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (ViewBag.FeedbackMensagem != null)
    {
        @Html.Raw("<script>");
        @Html.Raw("popFeedbackAlert('" + ViewBag.FeedbackStatus + "', '" + ViewBag.FeedbackMensagem + "');");
        @Html.Raw("</script>");
    }

    <script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
    </script>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
    <style type="text/css">
        .form-style-8 {
            font-family: 'Open Sans Condensed', arial, sans;
            width: 500px;
            padding: 30px;
            background: #FFFFFF;
            margin: 50px auto;
            box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.22);
            -moz-box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.22);
            -webkit-box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.22);
        }

            .form-style-8 h2 {
                background: #4D4D4D;
                text-transform: uppercase;
                font-family: 'Open Sans Condensed', sans-serif;
                color: #797979;
                font-size: 18px;
                font-weight: 100;
                padding: 20px;
                margin: -30px -30px 30px -30px;
            }

            .form-style-8 input[type="text"],
            .form-style-8 input[type="date"],
            .form-style-8 input[type="datetime"],
            .form-style-8 input[type="email"],
            .form-style-8 input[type="number"],
            .form-style-8 input[type="search"],
            .form-style-8 input[type="time"],
            .form-style-8 input[type="url"],
            .form-style-8 input[type="password"],
            .form-style-8 textarea,
            .form-style-8 select {
                box-sizing: border-box;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                outline: none;
                display: block;
                width: 100%;
                padding: 7px;
                border: none;
                border-bottom: 1px solid #ddd;
                background: transparent;
                margin-bottom: 10px;
                font: 16px Arial, Helvetica, sans-serif;
                height: 45px;
            }

            .form-style-8 textarea {
                resize: none;
                overflow: hidden;
            }

            .form-style-8 input[type="button"],
            .form-style-8 input[type="submit"] {
                -moz-box-shadow: inset 0px 1px 0px 0px #45D6D6;
                -webkit-box-shadow: inset 0px 1px 0px 0px #45D6D6;
                box-shadow: inset 0px 1px 0px 0px #45D6D6;
                background-color: #2CBBBB;
                border: 1px solid #27A0A0;
                display: inline-block;
                cursor: pointer;
                color: #FFFFFF;
                font-family: 'Open Sans Condensed', sans-serif;
                font-size: 14px;
                padding: 8px 18px;
                text-decoration: none;
                text-transform: uppercase;
            }

                .form-style-8 input[type="button"]:hover,
                .form-style-8 input[type="submit"]:hover {
                    background: linear-gradient(to bottom, #34CACA 5%, #30C9C9 100%);
                    background-color: #34CACA;
                }
    </style>

    @Html.ActionLink("Voltar à lista", "DocumentsList", "Document")
    <div class="form-style-8">
        <h2>Cadastrar novo documento</h2>
        <fieldset>
            @Html.ValidationSummary(true, "Houve um erro ao processar o formulário", new { @class = "alert warning" })
            <section>
                @Html.TextBoxFor(m => m.Codigo, new { type = "text", name = "field1", placeholder = @Html.DisplayNameFor(modelItem => modelItem.Codigo) })
                @Html.ValidationMessageFor(model => model.Codigo)
            </section>
            <section>
                @Html.TextBoxFor(m => m.Titulo, new { type = "text", name = "field2", placeholder = @Html.DisplayNameFor(modelItem => modelItem.Titulo) })
                @Html.ValidationMessageFor(model => model.Titulo)
            </section>
            <section>
                @Html.TextBoxFor(m => m.Processo, new { type = "text", name = "field3", placeholder = @Html.DisplayNameFor(modelItem => modelItem.Processo) })
                @Html.ValidationMessageFor(model => model.Processo)
            </section>
            <section>
                @Html.TextBoxFor(m => m.Categoria, new { type = "text", name = "field4", placeholder = @Html.DisplayNameFor(modelItem => modelItem.Categoria) })
                @Html.ValidationMessageFor(model => model.Categoria)
            </section>
            <section>
                @Html.TextBoxFor(m => m.Arquivo, new { type = "file"})
                @Html.ValidationMessageFor(model => model.Arquivo)
            </section>
            <br />
            <input type="submit" class="submit" name="submitbuttonname" value="Salvar documento" />
        </fieldset>
    </div>
}

QualyTeamWebSite/QualyTeam.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciador de Documentos</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />*@
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/vendor/perfect-scrollbar/perfect-scrollbar.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/colorlib/css/main.css">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script>
		function popFeedbackAlert(status, message){
		    window.alert('Status: ' + status + ' - Mensagem: ' + message);
		}
    </script>
    </script>
</head>
<body>
    @RenderBody()
    <hr />
    <footer>
        <p align="center">&copy; @DateTime.Now.Year - QualyTeam</p>
    </footer>


    <!--===============================================================================================-->
    <script src="~/Content/colorlib/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/colorlib/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/colorlib/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/colorlib/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/colorlib/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script>
		$('.js-pscroll').each(function(){
			var ps = new PerfectScrollbar(this);

			$(window).on('resize', function(){
				ps.update();
			})
		});
    </script>
    <!--===============================================================================================-->
    <script src="~/Content/colorlib/js/main.js"></script>
</body>
</html>